export const mockData = [
  {
    id: 1,
    image: "https://randomuser.me/api/portraits/women/55.jpg",
    name: "Sophia Williams",
    location: "Los Angeles, CA",
    bio: "Fitness enthusiast sharing workouts and healthy lifestyle tips.",
    category: "Fitness",
    email: "sophia.williams@example.com",
    website: "https://sophiafit.com",
  },
  {
    id: 2,
    image: "https://randomuser.me/api/portraits/women/55.jpg",
    name: "Ethan Brooks",
    location: "New York, NY",
    bio: "Photographer capturing urban and lifestyle moments.",
    category: "Photography",
    email: "ethan.brooks@example.com",
    website: "https://ethansnaps.com",
  },
  {
    id: 3,
    image: "https://randomuser.me/api/portraits/women/55.jpg",
    name: "Lila Chen",
    location: "San Francisco, CA",
    bio: "Tech enthusiast blogging about gadgets and innovations.",
    category: "Technology",
    email: "lila.chen@example.com",
    website: "https://lilatechreviews.com",
  },
  {
    id: 4,
    image: "https://randomuser.me/api/portraits/women/55.jpg",
    name: "Marcus Brown",
    location: "Austin, TX",
    bio: "Chef creating mouthwatering recipes and food styling.",
    category: "Food",
    email: "marcus.brown@example.com",
    website: "https://marcusbites.com",
  },
  {
    id: 5,
    image: "https://randomuser.me/api/portraits/women/55.jpg",
    name: "Emma Johnson",
    location: "Chicago, IL",
    bio: "Fashion designer showcasing minimalist and chic styles.",
    category: "Fashion",
    email: "emma.johnson@example.com",
    website: "https://emmajohnsonstyles.com",
  },
  {
    id: 6,
    image: "https://randomuser.me/api/portraits/women/55.jpg",
    name: "Ryan Cooper",
    location: "Seattle, WA",
    bio: "Travel vlogger exploring hidden gems around the world.",
    category: "Travel",
    email: "ryan.cooper@example.com",
    website: "https://ryanexplorer.com",
  },
  {
    id: 7,
    image: "https://randomuser.me/api/portraits/women/55.jpg",
    name: "Mia Torres",
    location: "Miami, FL",
    bio: "Beauty guru sharing makeup tips and skincare routines.",
    category: "Beauty",
    email: "mia.torres@example.com",
    website: "https://glamwithmia.com",
  },
  {
    id: 8,
    image: "https://randomuser.me/api/portraits/women/55.jpg",
    name: "Liam Harris",
    location: "Denver, CO",
    bio: "Outdoorsman documenting hiking and camping adventures.",
    category: "Adventure",
    email: "liam.harris@example.com",
    website: "https://liamhikes.com",
  },
  {
    id: 9,
    image: "https://randomuser.me/api/portraits/women/55.jpg",
    name: "Ava Martinez",
    location: "San Diego, CA",
    bio: "Pet lover featuring adorable content with her golden retriever.",
    category: "Pets",
    email: "ava.martinez@example.com",
    website: "https://avaandbuddy.com",
  },
  {
    id: 10,
    image: "https://randomuser.me/api/portraits/women/55.jpg",
    name: "Noah Green",
    location: "Portland, OR",
    bio: "Sustainability advocate promoting eco-friendly living.",
    category: "Sustainability",
    email: "noah.green@example.com",
    website: "https://noahgreenliving.com",
  },
];
